---
sudo: false
language: ruby
cache: bundler
gemfile:
  - gemfiles/dry_struct_4.gemfile
  - gemfiles/dry_struct_5.gemfile
script: bundle exec rspec
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.16.5
